vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        products:
            uri_prefix: /uploads/peintures
            upload_destination: '%kernel.project_dir%/public/uploads/peintures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
